spring:
  datasource:
    # url: jdbc:h2:file:./h2/h2data #サーバ起動でない場合はこちら
    url: jdbc:h2:tcp://localhost/./h2data #サーバ起動中はこちら
    driverClassName: org.h2.Driver
    username: sa
    password:
  batch:
    job:
      enabled: false

app:
  batch:
    # cron: 0/10 * * * * *
    # cron: "-" # 無効化する場合